from pathlib import Path

MOBILE = Path("app/src/main/java/com/streamflixreborn/streamflix/fragments/player/PlayerMobileFragment.kt")
TV = Path("app/src/main/java/com/streamflixreborn/streamflix/fragments/player/PlayerTvFragment.kt")


def r(path: Path, old: str, new: str, label: str) -> None:
    text = path.read_text()
    count = text.count(old)
    if count != 1:
        raise RuntimeError(f"{label}: expected one match, found {count}")
    path.write_text(text.replace(old, new, 1))


r(MOBILE, "    private var listenerPlayer: ExoPlayer? = null\n", "    private var listenerPlayer: ExoPlayer? = null\n    private var pendingPlaybackPositionMs: Long? = null\n", "mobile position field")
r(MOBILE, '''                    is PlayerViewModel.State.LoadingVideo -> {\n                        player.setMediaItem(\n''', '''                    is PlayerViewModel.State.LoadingVideo -> {\n                        if (pendingPlaybackPositionMs == null) {\n                            val currentUri = player.currentMediaItem?.localConfiguration?.uri?.toString().orEmpty()\n                            if (currentUri.isNotBlank()) {\n                                pendingPlaybackPositionMs = player.currentPosition\n                            }\n                        }\n\n                        player.setMediaItem(\n''', "mobile position capture")
r(MOBILE, '''                    is PlayerViewModel.State.SuccessLoadingVideo -> {\n                        PlayerSettingsView.Settings.ExtraBuffering.init(state.video.extraBuffering)\n                        PlayerSettingsView.Settings.SoftwareDecoder.init(false)\n                        displayVideo(state.video, state.server)\n                        playbackSourceRecoveryInProgress = false\n                    }\n''', '''                    is PlayerViewModel.State.SuccessLoadingVideo -> {\n                        PlayerSettingsView.Settings.ExtraBuffering.init(state.video.extraBuffering)\n                        PlayerSettingsView.Settings.SoftwareDecoder.init(false)\n                        val resumePosition = pendingPlaybackPositionMs\n                        pendingPlaybackPositionMs = null\n                        displayVideo(state.video, state.server, resumePosition)\n                        playbackSourceRecoveryInProgress = false\n                    }\n''', "mobile position success")
r(MOBILE, '''        playbackSourceRecoveryInProgress = false\n        Toast.makeText(\n''', '''        playbackSourceRecoveryInProgress = false\n        pendingPlaybackPositionMs = null\n        Toast.makeText(\n''', "mobile position clear")
r(MOBILE, "    private fun displayVideo(video: Video, server: Video.Server) {\n", "    private fun displayVideo(video: Video, server: Video.Server, startPositionMs: Long? = null) {\n", "mobile position signature")
r(MOBILE, '''        val currentPosition = player.currentPosition\n\n        httpDataSource.setDefaultRequestProperties(\n''', '''        val currentPosition = startPositionMs ?: player.currentPosition\n\n        httpDataSource.setDefaultRequestProperties(\n''', "mobile display position")
r(MOBILE, '''        })\n\n        if (currentPosition == 0L) {\n''', '''        })\n\n        if (startPositionMs != null) {\n            player.seekTo(startPositionMs)\n        } else if (currentPosition == 0L) {\n''', "mobile display seek")

# TV already has startPositionMs support upstream; only preserve the source-switch position through Loading/Success state.
r(TV, "    private var listenerPlayer: ExoPlayer? = null\n", "    private var listenerPlayer: ExoPlayer? = null\n    private var pendingPlaybackPositionMs: Long? = null\n", "tv position field")
r(TV, '''                        is PlayerViewModel.State.LoadingVideo -> {\n                            player.setMediaItem(\n''', '''                        is PlayerViewModel.State.LoadingVideo -> {\n                            if (pendingPlaybackPositionMs == null) {\n                                val currentUri = player.currentMediaItem?.localConfiguration?.uri?.toString().orEmpty()\n                                if (currentUri.isNotBlank()) {\n                                    pendingPlaybackPositionMs = player.currentPosition\n                                }\n                            }\n\n                            player.setMediaItem(\n''', "tv position capture")
r(TV, '''                        is PlayerViewModel.State.SuccessLoadingVideo -> {\n                            PlayerSettingsView.Settings.ExtraBuffering.init(state.video.extraBuffering)\n                            PlayerSettingsView.Settings.SoftwareDecoder.init(false)\n                            displayVideo(state.video, state.server)\n                            playbackSourceRecoveryInProgress = false\n                        }\n''', '''                        is PlayerViewModel.State.SuccessLoadingVideo -> {\n                            PlayerSettingsView.Settings.ExtraBuffering.init(state.video.extraBuffering)\n                            PlayerSettingsView.Settings.SoftwareDecoder.init(false)\n                            val resumePosition = pendingPlaybackPositionMs\n                            pendingPlaybackPositionMs = null\n                            displayVideo(state.video, state.server, startPositionMs = resumePosition)\n                            playbackSourceRecoveryInProgress = false\n                        }\n''', "tv position success")
r(TV, '''        playbackSourceRecoveryInProgress = false\n        Toast.makeText(\n''', '''        playbackSourceRecoveryInProgress = false\n        pendingPlaybackPositionMs = null\n        Toast.makeText(\n''', "tv position clear")
